[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  minify = true

[build.processing.html]
  pretty_urls = false

[build.processing.images]
  compress = true

[build.processing.js]
  bundle = false
  minify = true
